### ISSUE TITLE
First two sections doesn't display properly.

### ISSUE THREAD

**Issue by JHerseth** [sbugzu/gruvbox-zsh#2]
Hi. Awesome theme, but i'm experiencing some issues:
![img](https://i.imgur.com/iM9GSXY.png)

Any idea what's happening? I'm running pengwin linux on WSL2.

**Comment by sbugzu** [comment]
You should install one of [Nerd Fonts](https://www.nerdfonts.com/) first.
Then configure your terminal to use the font.

**Comment by JHerseth** [comment]
Thanks. Seems I have to figure out how to patch the font on my own, since I'm using PragmataPro. Should be doable :)
