### ISSUE TITLE
Theme always displays apple logo

### ISSUE THREAD

**Issue by JHerseth** [sbugzu/gruvbox-zsh#3]
https://github.com/sbugzu/gruvbox-zsh/blob/ee2daa9acb1448bc42d643b41b518dfd16984ca5/gruvbox.zsh-theme#L94

The OS logo is hardcoded. 
Maybe you could do something like this?
```
case "$OSTYPE" in
  darwin*)  OS_LOGO="\ue29e" ;; 
  linux*)   OS_LOGO="\ue712" ;;
esac
prompt_segment 237 7 $OS_LOGO
```

I'm not comfortable with git yet, or else I would have made a PR.

edit: Created a PR

**Comment by sbugzu** [comment]
Thank you for the PR.

**Comment by sbugzu** [comment]
Thank you for the PR.
