### ISSUE TITLE
Show only current directory instead of current path.

### ISSUE THREAD

**Issue by AmitDigga** [sbugzu/gruvbox-zsh#5]
![Capture](https://user-images.githubusercontent.com/7884106/85927219-51935e00-b8c2-11ea-9332-e20236ab8558.PNG)

For above case only `node_modules/ master` should have been there instead of whole path. When using split plane most of the space is occupied by the path itself.

**Comment by sbugzu** [comment]
A little modification:
`prompt_segment 4 $CURRENT_FG '%~'`
to
`prompt_segment 4 $CURRENT_FG '%c'`
