### ISSUE TITLE
Virtual environment segment doesn't display properly

### ISSUE THREAD

**Issue by hectorBrown** [sbugzu/gruvbox-zsh#6]
Hi, awesome theme... one small thing, my virtualenv doesn't display with background or separator. I tried messing about with this but couldn't fix it myself.
![image](https://user-images.githubusercontent.com/45634793/221652622-345b0ffd-2f31-4440-86b4-4b5761ad6c03.png)

**Comment by sbugzu** [comment]
Because this is a virtualenv appended directly to prompt, we just need to disable it.
Append the following to `~/.zshrc` or any other file that can modify environment variables
```shell
export VIRTUAL_ENV_DISABLE_PROMPT=1
```

BTW, I updated the style of virtualenv today, enjoy it!

**Comment by hectorBrown** [comment]
Yeah that works perfectly thanks, much prefer the new venv colour.

**Comment by hectorBrown** [comment]
![image](https://user-images.githubusercontent.com/45634793/222525239-31e9418c-3794-4c33-ab37-c0f7509084bc.png)
Also, wrote some VCS stuff to get details on untracked files, numbers, whether ahead or behind remotes etc. 
Can submit a PR if wanted, but if you'd prefer to keep it cleaner no worries.

**Comment by sbugzu** [comment]
> ![image](https://user-images.githubusercontent.com/45634793/222525239-31e9418c-3794-4c33-ab37-c0f7509084bc.png) Also, wrote some VCS stuff to get details on untracked files, numbers, whether ahead or behind remotes etc. Can submit a PR if wanted, but if you'd prefer to keep it cleaner no worries.

That's a great feature. Submit the PR freely.
